### ISSUE TITLE
BPS calculator gives imprecise results for high speeds

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#112]
In this test level
https://yadi.sk/d/igPETEleqjKxh
there are two crushers with player start position between them. Both crushers are set to move up at 2 bps for 6 seconds then down at 12 bps for 1 second and loop repeats. After long run left crusher goes out of synth and stops hitting floor after some time. This is because left crusher goes down at speed of 
5.90769 pixels per tick (BpS calculation result left as is), while right one goes down at speed of 5.975 pixels per tick (fine-tuned manually for better result).

**Comment by Wohlstand** [comment]
I think, I would allow better precission, but don't forget that limit is precision of double C type

**Comment by Bluenaxela** [comment]
While we're at it, I'll note that the BPS calculator in the PGE Editor is using 65FPS for it's calculations, but this is incorrect for how SMBX behaves.

SMBX runs with 15.6ms per tick (approximately 64.1025641)

If you switch the PGE Editor to use 15.6ms instead of 65FPS for the calculation, you should get 5.9904 pixels per tick exactly, in place of approximately 5.907692307692308.

As such, I expect switching to the more correct 15.6ms will also give nicer pixel per tick numbers that are less likely to get out of sync.

**Comment by Wohlstand** [comment]
So, Rednaxela, I completely need to recalculate lots of parameters in physics also too :stuck_out_tongue_winking_eye: 
I fixed calculation in the editor to values based on "1000.0/15.6" frames per second value, but I need to replace "1000.0/65.0" frame time in some scripts
