### ISSUE TITLE
Portal + 2-way warp => inescapable trap

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#113]
Character can get trapped by getting teleported back&forth by the same 2-way portal warp with zero delay.

**Comment by Wohlstand** [comment]
Ouch, let me fix that

**Comment by Wohlstand** [comment]
Fixed, wait while laboratory build will be rebuilt (AppVeyor builds editor only, my own server builds same in 1.5 hours [pretty slow, because MinGW under wine, windeployqt is not works with cross-compiler, but... I would to build PGE with a cross compiler, but run windeployqt with Wine, that will boost build speed, so, I'll try to setup that later])
