### ISSUE TITLE
Windows Online Installer Overwrites entire system PATH Environment Variable

### ISSUE THREAD

**Issue by KytechN24** [Wohlhabend-Networks/PGE-Project#120]
After running the Online Installer for PGE from [this page](http://wohlsoft.ru/PGE/#links), my system's PATH environment variable is changed to contain exactly this: 

> "C:\Program Files (x86)\PGE"

The installer deletes all other entries in the PATH environment variable including the system defaults such as "C:\Windows\System32", messing up any terminal and development environments on my system. PGE seems to run fine without being in the PATH variable since I do not have this issue when downloading the portable.zip version or by using the Online Installer and then removing the PGE installation folder from the PATH variable. The installer shouldn't mess up a system's PATH environment variable. It would be even better if PGE doesn't need to be in the PATH variable at all.

**Comment by Wohlstand** [comment]
That bug was in early builds on installer and I fixed it, are you still have it? Which Windows version you have?

**Comment by Wohlstand** [comment]
Just now I made adding to PATH environment to be optional and disabled by default, wait until I will come to the job and then I'll upload fixed installer to everywhere

**Comment by KytechN24** [comment]
Ok. Thanks! The Windows version I am running is Windows 10 Pro (64 bit) if you still need this information. I will watch for the fixed installer.

**Comment by Wohlstand** [comment]
That thing works perfect in Windows XP, 7, 8, 8.1, but never tested on Windows 10. I think it's an answer to a question why this bug appears again, because this will work differently: (fragment of NSIS script )
```NSIS
;Add PATH variables
ReadRegStr $0 HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment" 'Path'
${StrContains} $2 $INSTDIR $0
StrCmp $2 "" needtoaddpath
    goto pathalreadyadded
needtoaddpath:
    StrCpy $1 "$0;$INSTDIR"
WriteRegStr HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment" 'Path' $1
pathalreadyadded:
```
Where used this function:
http://nsis.sourceforge.net/StrContains
So, I also added support of portable mode to store everything into same folder and use portable INI configs

**Comment by Wohlstand** [comment]
EDIT: updated installer has been sent!
Redownload and retry it!
Now it supports remembering of previously installed components and there are will kept checked state on attempt to run installer second time, with portable mode it will use INI-file at same directory to save settings instead of registry usage

**Comment by Wohlstand** [comment]
Fixed installer path: http://wohlsoft.ru/PGE/_downloads/win32/pge-online-downloader.exe
(I accidentally forgot to replace url on main page)
