### ISSUE TITLE
Issues with P-Switch

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#141]
- [x] 1. Character can pass through transformed solid brick blocks.
![scr_2016_9_6_12_34_56_100](https://cloud.githubusercontent.com/assets/7596025/18281893/56c07ef6-7467-11e6-8de9-5f8b2725525e.png)

- [x] 2. Weird things happen if P-Switch was used in conjunction with layers and events, like "hit P-switch and collect all coins before timer expires for reward" challenge. Glitches like premature reward event triggering, coins not disappearing with layer etc.

Test level: https://yadi.sk/d/zxuGvxrsuqTD2

**Comment by Wohlstand** [comment]
Ouch, I totally forgot to fix that...
I knew that bug and it's a bug of transforming which seems repluged elements to the another layer therefore layer manager wasn't able to hide them. Also I forgot to re-enable collision for undestroyed blocks

**Comment by Wohlstand** [comment]
Both issues are been caused by same imperfection set which I just resolved. Also I fixed P-Switch script to don't transform hidden elements (and also I triggering "P-Switch End" event on last frame of P-Switch time that avoids transforming of hidden elements).
Fun fact: in SMBX a strong bug when playing around P-Switch and hidden/shown layer:
https://www.youtube.com/watch?v=uL1FbgqHZJo
In PGE Engine this never happens (on fixed version, where you also need to take fresh p-switch.lua into all your config packs to don't transform blocks and coins before layer will be hidden)

**Comment by Wohlstand** [comment]
So, I just playd your demo level and everything now works perfect
(to correctly process red bonus coins, you must update p-switch.lua, because that swaps sequence of transforming stuff and calling "P-Switch end" event)

**Comment by Wohlstand** [comment]
That has been fixed and no more causes bugs. Also I rejected transforming elements in hidden layers (like SMBX Engine doing)
