### ISSUE TITLE
Wierd displaying of cyrillic letters in message boxes.

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#59]
Created message block with some cyrillic text in it. It is displayed fine in the editor. But in the engine, we got this:
![scr_2015_7_29_14_46_49_35](https://cloud.githubusercontent.com/assets/7596025/8961913/8d6b78ce-3620-11e5-92ca-75c740fdb2eb.png)
Test level: https://yadi.sk/d/xuRbAoMTiAFmi

**Comment by Wohlstand** [comment]
The reason is not made cyrilic font map for a "font2" wasn't made, therefore just used TTF font, but how you see, result is nosense. I made cyrilic font maps for a menu font1. Here placed all created fonts:
https://github.com/Wohlhabend-Networks/PGE-Project/tree/master/Content/configs/SMBX/fonts
in your config pack it's a "configs/SMBX/fonts" or "configs/Raocow (A2MBXT)/fonts". When I will come to home, I will make cyrilic version of font2 now, it's important for us.

**Comment by Wohlstand** [comment]
Fixed ;-) https://github.com/Wohlhabend-Networks/PGE-Project/commit/9718762dadf7868ef822b10b06c1ac42b1f4563d
I just made Cyrillic map for font2 which uses by message boxes, now everything showing fine :wink: 
![scr_2015_8_1_21_34_16_676](https://cloud.githubusercontent.com/assets/6751442/9023066/32058732-3895-11e5-977d-4b2f81f25727.png)
