### ISSUE TITLE
Middle mouse button and item properties issue

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#63]
Whenever you try to select an item for duplicating it via middle mouse button ("Switch placing mode of the selected item" in editor options), the function does not account item properties, like container contents, event trigger slots etc, and always use default ones for placing new items. It`s not uncommon to see objects not disappearing with layer during testing and then discovering they are on wrong layer due to this.

**Comment by cramps-man** [comment]
It seems what happens here is that when you select then middle click mouse button, the "placing new item" mode is in place. It also copies the data of the item into the clipboard though, so you can press ctrl-v to paste the item and it will copy correctly. 

The issue here is that it shouldn't enter both options of "switch placing mode of the selected item" and the "duplicate selected items into mouse position" at the same time. 

A solution might be to fix the editor options to allow only one or none of these 2 options; via radio button perhaps?

**Comment by cramps-man** [comment]
Well I've devised a fix for the problem by making the 2 options into radio buttons. I think it works as intended now so I guess this can be closed now?

**Comment by Alucard648** [comment]
I don`t think, it will be a proper solution for this issue. The behaviour for middle mouse button, assuming all 3 options in app settings are on, should be like this:
1. If no items selected - switch to Drag Scroll.
2. If already in Drag Scroll mode - switch back to Select mode.
3. If exactly one item selected - get that item`s properties and switch to placing mode with item in the hand.
4. If more than one item selected - Duplicate selected items into mouse position.

**Comment by Wohlstand** [comment]
The solution is a copying of current itemset into LvlItemPlacing::BlockSet or BgoSet or NpcSet which used as holding of properties for futured items

**Comment by Wohlstand** [comment]
Just made support of settings inheriting from selected item, but on levels only yet. Also with new update is possible to switch into selection mode from hand-drag with right mouse button

**Comment by Wohlstand** [comment]
Everything has been fixed/solved
