### ISSUE TITLE
Off-screen lava does not kill player characters and NPC`s

### ISSUE THREAD

**Issue by Alucard648** [Wohlhabend-Networks/PGE-Project#64]
![scr_2015_8_12_23_41_1_8](https://cloud.githubusercontent.com/assets/7596025/9236253/5a782f7a-414c-11e5-8efc-52732cf989ca.png)
![offscreenlavabug1](https://cloud.githubusercontent.com/assets/7596025/9236256/5ec375bc-414c-11e5-9c98-666f51f3a013.png)
Screenshots say all.
Test level: https://yadi.sk/d/opuZ6jwDiRFxL

**Comment by Wohlstand** [comment]
Since PGE Engine 0.1 with new physical engine lava no more kills player and NPC's because I disabled killing condition on contact with lava blocks because there are preventing to test waling. I will implement that later, when I will finally move cheating things like unlimited flying and super-tail into Chuck Norris Cheating zone since I added text-input box....where I or Bossedit8 will type that cheats (he LOVE super-tail to destroy everything xD). And with some other small things, PGE Engine will be finally playable engine with true game environment where character can fail or dead on contact with dangerous objects, etc.
